<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>Bipolar.InterfaceSerialization.SourceGeneration</RootNamespace>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <ILMerge>false</ILMerge>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference ExcludAssets="runtime" Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" PrivateAssets="all" />
    </ItemGroup>
</Project>
