using Microsoft.CodeAnalysis;
using System.CodeDom.Compiler;
using System.IO;
using System.Linq;

namespace Bipolar.InterfaceSerialization.SourceGeneration
{
    public static class SerializedInterfaceClassSourceGenerator
    {
        public const string SerializedInterfaceClassName = "SerializedInterface";
    
        public static string GenerateSource(string? namespaceName, string className, string interfaceName, INamedTypeSymbol interfaceSymbol, bool isPartial = false)
        {
            var textWriter = new StringWriter();
            var codeWriter = new IndentedTextWriter(textWriter);
            bool hasNamespace = !string.IsNullOrWhiteSpace(namespaceName) && namespaceName != "<global namespace>";

            codeWriter.WriteLine("// <auto-generated/>");
            codeWriter.WriteLine();
            if (hasNamespace)
            {
                codeWriter.WriteLine($"namespace {namespaceName}");
                codeWriter.WriteLine("{");
                codeWriter.Indent++;
            }

            codeWriter.WriteLine("[System.Serializable]");
            codeWriter.Write($"public sealed ");
            if (isPartial)
                codeWriter.Write($"partial ");
            codeWriter.WriteLine($"class {className} : Bipolar.{SerializedInterfaceClassName}<{interfaceName}>, {interfaceName}");
            codeWriter.WriteLine("{");
            codeWriter.Indent++;
            WriteMemebers(codeWriter, interfaceSymbol);
            codeWriter.Indent--;
            codeWriter.WriteLine("}");

            if (hasNamespace)
            {
                codeWriter.Indent--;
                codeWriter.WriteLine("}");
            }

            return textWriter.ToString();
        }

        private static void WriteMemebers(IndentedTextWriter writer, INamedTypeSymbol symbol)
        {
            var members = symbol.GetMembers();
            bool isFirstIteration = true;

            bool hasMemberNamedValue = members
                .Where(m => m is IPropertySymbol || m is IMethodSymbol)
                .Any(m => m.Name == "Value");

            string valueText = hasMemberNamedValue ? "base.Value" : "Value";
            foreach (var member in members)
            {
                if (member is IMethodSymbol method && method.MethodKind == MethodKind.Ordinary)
                {
                    WriteOptionalEmptyLine();
                    WriteMethod(method);
                }
                else if (member is IPropertySymbol property)
                {
                    WriteOptionalEmptyLine();
                    WriteProperty(property);
                }
                else if (member is IEventSymbol @event)
                {
                    WriteOptionalEmptyLine();
                    WriteEvent(@event);
                }
            }

            void WriteOptionalEmptyLine()
            {
                if (isFirstIteration == false)
                    writer.WriteLine();
                isFirstIteration = false;
            }

            void WriteMethod(IMethodSymbol method)
            {
                string returnTypeName = method.ReturnType.ToDisplayString();
                string methodName = method.Name;

                var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
                var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));

                writer.Write($"public ");
                if (methodName == "Value")
                    writer.Write($"new ");

                writer.WriteLine($"{returnTypeName} {methodName}({parameters}) => {valueText}.{methodName}({arguments});");
            }

            void WriteProperty(IPropertySymbol property)
            {
                string returnTypeName = property.Type.ToDisplayString();
                string propertyName = property.Name;

                bool hasGet = property.GetMethod != null;
                bool hasSet = property.SetMethod != null;

                writer.Write($"public ");
                if (propertyName == "Value")
                    writer.Write($"new ");

                writer.Write($"{returnTypeName} {propertyName}");
                if (hasGet && hasSet)
                {
                    writer.WriteLine();
                    writer.WriteLine("{");
                    writer.Indent++;
                    writer.WriteLine($"get => {GetGetterBody()}");
                    writer.WriteLine(GetSetterImplementation());
                    writer.Indent--;
                    writer.WriteLine("}");
                }
                else if (hasGet)
                {
                    writer.WriteLine(GetGetterBody());
                }
                else if (hasSet)
                {
                    writer.WriteLine($" {{ {GetSetterImplementation()} }}");
                }

                string GetSetterImplementation()
                {
                    return $"set => {valueText}.{propertyName} = value;";
                }

                string GetGetterBody()
                {
                    return $" => {valueText}.{propertyName};";
                }
            }

            void WriteEvent(IEventSymbol @event)
            {
                var eventTypeName = @event.Type.ToDisplayString();
                var eventName = @event.Name;

                writer.WriteLine($"public event {eventTypeName} {eventName}");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"add => {valueText}.{eventName} += value;");
                writer.WriteLine($"remove => {valueText}.{eventName} -= value;");
                writer.Indent--;
                writer.WriteLine("}");
            }
        }
    }
}
